<?php


return [
    [
        'icon' => 'nav-icon fas fa-tachometer-alt',
        'route' => 'dashboard',
        'title' => 'Dashboard',
        'active' => 'dashboard',
        'user'=>true,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'user.index',
        'title' => 'Users',
        'active' => 'user.index',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'user.create',
        'title' => 'Create',
        'active' => 'user.create',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'user.trash',
        'title' => 'Trash',
        'active' => 'user.trash',
        'badge' => 'New',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'nav-icon fas fa-tachometer-alt',
        'route' => 'vendors.index',
        'title' => 'Vendors',
        'active' => 'vendors.index',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'vendors.create',
        'title' => 'Create Vendor',
        'active' => 'vendors.create',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'vendors.trash',
        'title' => 'Vendors Trash',
        'active' => 'vendors.trash',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'nav-icon fas fa-chart-pie',
        'route' => 'brands.index',
        'title' => 'Brands',
        'active' => 'brands.index',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'brands.create',
        'title' => 'Create Brand',
        'active' => 'brands.create',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'brands.trash',
        'title' => 'Brands Trash',
        'active' => 'brands.trash',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'nav-icon fas fa-tree',
        'route' => 'items.index',
        'title' => 'Items',
        'active' => 'items.index',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'items.create',
        'title' => 'Create Item',
        'active' => 'items.create',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'items.trash',
        'title' => 'Items Trash',
        'active' => 'items.trash',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'nav-icon fas fa-tachometer-alt',
        'route' => 'inventories.index',
        'title' => 'Inventories',
        'active' => 'inventories.index',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'inventories.create',
        'title' => 'Create Inventory',
        'active' => 'inventories.create',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'inventories.trash',
        'title' => 'Inventories Trash',
        'active' => 'inventories.trash',
        'user'=>false,
        'admin'=>true,
    ],
    [
        'icon' => 'nav-icon fas fa-tree',
        'route' => 'front.items.index',
        'title' => 'Items',
        'active' => 'front.items.index',
        'user'=>true,
        'admin'=>false,
    ],
    [
        'icon' => 'far fa-circle nav-icon',
        'route' => 'front.cart.index',
        'title' => 'Cart',
        'active' => 'front.cart.index',
        'user'=>true,
        'admin'=>false,
    ],
];
